name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
          jobs:
            display time:
           runs-on: ubuntu-20.04   
          steps:
            -name:display time1
            run: |
            echo "time now is"
